### ISSUE TITLE
Visitor Log causing ValueError

### ISSUE THREAD

**Issue by AW20165** [TempeHS/The_Unsecure_PWA#1]
Hi, is the visitor log supposed to be empty? I get a ValueError: invalid literal for int() with base 10: '' when it tries to access the visitor log, `number` = int(file.read().strip()) is trying to convert the empty string to an int. Just editing the visitor_log.txt to have '1' fixes the issue.

**Comment by benpaddlejones** [comment]
Fixed with [commit](https://github.com/TempeHS/The_Unsecure_PWA/commit/35ce52d11cf5e46fd7805130d74504edcde608df)
